on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build and Deploy a Container to Google Compute Engine
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  INSTANCE: ${{ secrets.GCP_INSTANCE }}
  ZONE: us-east1-b

jobs:
  setup-build-publish-deploy:
    name: Setup Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker Push
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: docker build . -t gcr.io/${{ env.PROJECT_ID }}/${{ env.INSTANCE }}-image:${{ github.sha }}

      - name: Push Docker Image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.INSTANCE }}-image:${{ github.sha }}

      - name: Deploy to Google Compute Engine
        run: |-
          gcloud compute instances update-container ${{ env.INSTANCE }} \
            --container-image gcr.io/${{ env.PROJECT_ID }}/${{ env.INSTANCE }}-image:${{ github.sha }} \
            --zone ${{ env.ZONE }}
