name: Build and Deploy the Container to Google Compute Engine
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  INSTANCE: ${{ secrets.GCP_INSTANCE }}
  ZONE: us-east1-b

on:
  push:
    branches: [main]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up the Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Register Google Cloud SDK as a Docker credential helper
        run: gcloud auth configure-docker

      - name: Build the Docker image
        run: docker build . -t gcr.io/${{ env.PROJECT_ID }}/${{ env.INSTANCE }}-image:${{ github.sha }}

      - name: Publish the Docker image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.INSTANCE }}-image:${{ github.sha }}

      - name: Deploy to Google Compute Engine
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: http://${{ secrets.WEBHOOK_IP }}
          body: '{"secret": ${{ secrets.WEBHOOK_SECRET }} }'
